
package jprg_assignment;

public class StudentMainMenu extends javax.swing.JFrame {
    private Object[] studentObj;

    public StudentMainMenu(Object[] userObj) {
        initComponents();
        this.studentObj = userObj;
        // Prevent table's column from being movable
        tableDisplayInfo.getTableHeader().setReorderingAllowed(false);
        lblWelcome.setText("Welcome, " + userObj[1].toString() + "!");
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // Good bye sound effect
                SoundPlayer.playSound("SoundEffects\\\\Bye.wav");
                // Log Program termination
                UserActivityLogger.infoLog("Program Terminated");
                // Await Soundplayer duration
                try {
                    Thread.sleep(1200);
                } catch (InterruptedException ex) {
                    UserActivityLogger.errLog("Unable to sleep thread.", ex);
                }
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSearch = new javax.swing.ButtonGroup();
        tabpaneMain = new javax.swing.JTabbedPane();
        panelWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        panelText = new javax.swing.JPanel();
        lblText = new javax.swing.JLabel();
        lblDeveloper = new javax.swing.JLabel();
        panelDisplay = new javax.swing.JPanel();
        lblTitleDisplay = new javax.swing.JLabel();
        panelDisplayInfo = new javax.swing.JPanel();
        scrollpaneTable = new javax.swing.JScrollPane();
        tableDisplayInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        panelSearchStudent = new javax.swing.JPanel();
        lblTitleSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        radioStudents = new javax.swing.JRadioButton();
        radioModule = new javax.swing.JRadioButton();
        panelSearchInfo = new javax.swing.JPanel();
        scrollpaneMessages = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextPane();
        lblMessages = new javax.swing.JLabel();
        panelStatistics = new javax.swing.JPanel();
        panelSettings = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Singapore Polytechnic - Mini Student System");
        setResizable(false);

        tabpaneMain.setBackground(new java.awt.Color(255, 255, 255));
        tabpaneMain.setToolTipText(null);

        panelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        panelWelcome.setToolTipText(null);

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblWelcome.setText("Welcome");
        lblWelcome.setToolTipText(null);
        lblWelcome.setMaximumSize(new java.awt.Dimension(800, 65));
        lblWelcome.setMinimumSize(new java.awt.Dimension(800, 65));
        lblWelcome.setPreferredSize(new java.awt.Dimension(800, 65));

        panelText.setBackground(new java.awt.Color(255, 255, 255));
        panelText.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 1, true));
        panelText.setToolTipText(null);
        panelText.setMaximumSize(new java.awt.Dimension(975, 430));
        panelText.setMinimumSize(new java.awt.Dimension(975, 430));
        panelText.setPreferredSize(new java.awt.Dimension(975, 430));

        lblText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblText.setText("<html>\n<p>This is an implementation of a student management system using <strong><u>Java JDK 1.8</u></strong>, developed with <strong><u>NetBeans IDE 8.2</u></strong>.</p><br>\n<p>The implementation of this application is done for <strong>Singapore Polytechnic's Java Programming (JPRG) Module</strong>.</p><br>\n<p>This application is incorporated with <strong>Basic Features</strong> required by CA2's requirements:</p>\n<ul>\n<li>&ensp;<strong>Java Graphical User Interface (GUI)</strong> implementation using <i>JFrame, JLabel, JButton, etc</i>.</li>\n<li>&ensp;All basic features implemented in <strong>JPRG CA1</strong>, <i>Display All Students, Print Statistics, etc</i>.</li>\n<li>&ensp;<strong>File Input and Output (IO) system</strong>, including <strong>Serialization and Deserialization of Java Objects</strong>.</li>\n<li>&ensp;<strong>Java Inheritance Feature</strong></li>\n</ul>\n<p>This application is also incorporated with several <strong>Advanced Features</strong>:</p>\n<ul>\n<li><strong>Login System</strong>, this includes separate GUI for Admin / Non-Admin users.</li>\n<li><strong>Security System</strong>, this is an added feature to store information for Login system prior to Serialization. This is done via <strong>hashing of passwords using SHA-512 algorithym</strong> with added randomness with the use of <strong>random Salt per password</strong>.</li>\n<li>(Not implemented) <strong>Image Upload System</strong></li>\n<li>(Carried over from CA1) <strong>Sound Player System</strong></li>\n<li>(Carried over from CA1) <strong>User Activity Logger</strong></li>\n<li>(Carried over from CA1) <strong>Input Verification</strong></li>\n<li>(Carried over from CA1) <strong>Statistics Report Export</strong></li>\n</ul>\n<p>To start using the application, start navigating through all the tabs to experiment with its functions.</p>\n</html>");
        lblText.setToolTipText(null);
        lblText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelTextLayout = new javax.swing.GroupLayout(panelText);
        panelText.setLayout(panelTextLayout);
        panelTextLayout.setHorizontalGroup(
            panelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTextLayout.setVerticalGroup(
            panelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        lblDeveloper.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeveloper.setText("Developed by: Yam Kar Lok");
        lblDeveloper.setToolTipText(null);

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWelcomeLayout.createSequentialGroup()
                        .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblDeveloper)
                .addContainerGap())
        );

        tabpaneMain.addTab("Welcome Page", panelWelcome);

        panelDisplay.setToolTipText(null);

        lblTitleDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitleDisplay.setText("All Students Information:");
        lblTitleDisplay.setToolTipText(null);

        panelDisplayInfo.setToolTipText(null);
        panelDisplayInfo.setMaximumSize(new java.awt.Dimension(975, 495));
        panelDisplayInfo.setMinimumSize(new java.awt.Dimension(975, 495));
        panelDisplayInfo.setPreferredSize(new java.awt.Dimension(975, 495));

        scrollpaneTable.setToolTipText(null);

        tableDisplayInfo.setModel(StudentManagement.displayAllStudents());
        tableDisplayInfo.setToolTipText(null);
        scrollpaneTable.setViewportView(tableDisplayInfo);

        javax.swing.GroupLayout panelDisplayInfoLayout = new javax.swing.GroupLayout(panelDisplayInfo);
        panelDisplayInfo.setLayout(panelDisplayInfoLayout);
        panelDisplayInfoLayout.setHorizontalGroup(
            panelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        panelDisplayInfoLayout.setVerticalGroup(
            panelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        btnRefresh.setBackground(java.awt.Color.blue);
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.setToolTipText(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDisplayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitleDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDisplayLayout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addGap(18, 28, Short.MAX_VALUE))
                    .addGroup(panelDisplayLayout.createSequentialGroup()
                        .addComponent(lblTitleDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(panelDisplayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabpaneMain.addTab("Display All Students", panelDisplay);

        panelSearchStudent.setToolTipText(null);

        lblTitleSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitleSearch.setText("Search:");
        lblTitleSearch.setToolTipText(null);

        txtSearch.setToolTipText(null);
        txtSearch.setMinimumSize(new java.awt.Dimension(380, 40));
        txtSearch.setPreferredSize(new java.awt.Dimension(380, 40));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jprg_assignment/search.png"))); // NOI18N
        btnSearch.setToolTipText(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setMaximumSize(new java.awt.Dimension(40, 40));
        btnSearch.setMinimumSize(new java.awt.Dimension(40, 40));
        btnSearch.setPreferredSize(new java.awt.Dimension(40, 40));

        btnGroupSearch.add(radioStudents);
        radioStudents.setSelected(true);
        radioStudents.setText("By Students");
        radioStudents.setToolTipText(null);
        radioStudents.setMaximumSize(new java.awt.Dimension(150, 40));
        radioStudents.setMinimumSize(new java.awt.Dimension(150, 40));
        radioStudents.setPreferredSize(new java.awt.Dimension(150, 40));

        btnGroupSearch.add(radioModule);
        radioModule.setText("By Module");
        radioModule.setToolTipText(null);
        radioModule.setMaximumSize(new java.awt.Dimension(150, 40));
        radioModule.setMinimumSize(new java.awt.Dimension(150, 40));
        radioModule.setPreferredSize(new java.awt.Dimension(150, 40));

        panelSearchInfo.setToolTipText(null);

        txtMessages.setToolTipText(null);
        scrollpaneMessages.setViewportView(txtMessages);

        lblMessages.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMessages.setText("Messages:");
        lblMessages.setToolTipText(null);

        javax.swing.GroupLayout panelSearchInfoLayout = new javax.swing.GroupLayout(panelSearchInfo);
        panelSearchInfo.setLayout(panelSearchInfoLayout);
        panelSearchInfoLayout.setHorizontalGroup(
            panelSearchInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchInfoLayout.createSequentialGroup()
                .addGroup(panelSearchInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollpaneMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSearchInfoLayout.setVerticalGroup(
            panelSearchInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollpaneMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSearchStudentLayout = new javax.swing.GroupLayout(panelSearchStudent);
        panelSearchStudent.setLayout(panelSearchStudentLayout);
        panelSearchStudentLayout.setHorizontalGroup(
            panelSearchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchStudentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelSearchInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(panelSearchStudentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelSearchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSearchStudentLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(radioStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelSearchStudentLayout.setVerticalGroup(
            panelSearchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSearchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioModule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelSearchInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        tabpaneMain.addTab("Search", panelSearchStudent);

        panelStatistics.setToolTipText(null);

        javax.swing.GroupLayout panelStatisticsLayout = new javax.swing.GroupLayout(panelStatistics);
        panelStatistics.setLayout(panelStatisticsLayout);
        panelStatisticsLayout.setHorizontalGroup(
            panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        panelStatisticsLayout.setVerticalGroup(
            panelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        tabpaneMain.addTab("Statistics", panelStatistics);

        panelSettings.setToolTipText(null);

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        tabpaneMain.addTab("Profile Settings", panelSettings);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpaneMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpaneMain)
        );

        tabpaneMain.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Refresh Button">
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        tableDisplayInfo.setModel(StudentManagement.displayAllStudents());
    }//GEN-LAST:event_btnRefreshActionPerformed
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Static Student Menu">
    public static void studentMenu(Object[] userObj) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainMenu(userObj).setVisible(true);
            }
        });
    }
    // </editor-fold>
    
    public static void main(String[] args) {
        StudentManagement.initializeStudents();
        studentMenu(new Object[] {"1", "Testtesttesteteststestet"});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblDeveloper;
    private javax.swing.JLabel lblMessages;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTitleDisplay;
    private javax.swing.JLabel lblTitleSearch;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelDisplayInfo;
    private javax.swing.JPanel panelSearchInfo;
    private javax.swing.JPanel panelSearchStudent;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JPanel panelStatistics;
    private javax.swing.JPanel panelText;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JRadioButton radioModule;
    private javax.swing.JRadioButton radioStudents;
    private javax.swing.JScrollPane scrollpaneMessages;
    private javax.swing.JScrollPane scrollpaneTable;
    private javax.swing.JTable tableDisplayInfo;
    private javax.swing.JTabbedPane tabpaneMain;
    private javax.swing.JTextPane txtMessages;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
